### Create token
POST http://localhost:8080/auth HTTP/1.1
Content-Type: application/json 
{
  "email": "skarlet15m@gmail.com",
  "password": "D123@devs"
}

### Get data orders
GET http://localhost:8080/orders HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNrYXJsZXQxNW1AZ21haWwuY29tIiwiaWF0IjoxNjU1MTMxMjI3LCJleHAiOjE2NTUxMzg0Mjd9.zwWZIxKM2-if5-0kViWXnWaRnaaGlvYYEBjafH6Hba8
Content-Type: application/json

### Create orders
POST http://localhost:8080/orders HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNrYXJsZXQxNW1AZ21haWwuY29tIiwiaWF0IjoxNjU1MTMxMjI3LCJleHAiOjE2NTUxMzg0Mjd9.zwWZIxKM2-if5-0kViWXnWaRnaaGlvYYEBjafH6Hba8
Content-Type: application/json

{
  "client": "Juan",
  "table": "12",
  "total": "22.00",
  "status": "delivered",
  "hours": "11:27:53",
  "startTime": 1653323273796,
  "endTime": 1653324513486,
  "totalTime": 21,
  "products": [],
  "id": 17
}

### Edit orders
PUT http://localhost:8080/orders/62a3c1314cd916124084e1d3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNrYXJsZXQxNW1AZ21haWwuY29tIiwiaWF0IjoxNjU1MTMxMjI3LCJleHAiOjE2NTUxMzg0Mjd9.zwWZIxKM2-if5-0kViWXnWaRnaaGlvYYEBjafH6Hba8
Content-Type: application/json

{
  "status": "ready"
}

### Delete orders
DELETE http://localhost:8080/orders/62a753cdfa6364b5f9c6a63a HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNrYXJsZXQxNW1AZ21haWwuY29tIiwiaWF0IjoxNjU1MTMxMjI3LCJleHAiOjE2NTUxMzg0Mjd9.zwWZIxKM2-if5-0kViWXnWaRnaaGlvYYEBjafH6Hba8

