### 
GET http://localhost:8080/empleados/1 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NDYxMzM3MiwiZXhwIjoxNjU0NjIwNTcyfQ.C9jUUYSwFYk8oni-wJ1y2m3sELMRfls2z4rLsCaHBUA