### 
GET http://localhost:8080/menu HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsImlhdCI6MTY1NDU1Mzc1MCwiZXhwIjoxNjU0NTYwOTUwfQ.N77SUqoYl_hE2qf762uxOuBmEHtpMT2ak7zTjdBlFEo