### Generar token
POST http://localhost:8080/staffs HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NDY0ODY1MCwiZXhwIjoxNjU0NjU1ODUwfQ.zhR1uZ_Mw88adT1WALiiKC8zKHHHZviI8bH4lc89Yo4
Content-Type: application/json

{
  "role": "Mesero",
  "name": "Damian",
  "lastname": "Sala",
  "email": "damian@gmail.com",
  "date": "2022-06-07",
  "id": 10
}


### Crear usuario
POST http://localhost:8080/staffs HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NDY0ODY1MCwiZXhwIjoxNjU0NjU1ODUwfQ.zhR1uZ_Mw88adT1WALiiKC8zKHHHZviI8bH4lc89Yo4
Content-Type: application/json

{
  "role": "Mesero",
  "name": "Damian",
  "lastname": "Sala",
  "email": "damian@gmail.com",
  "date": "2022-06-07",
  "id": 10
}

### Pintar data
GET http://localhost:8080/staffs HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdCIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY1NDY0ODY1MCwiZXhwIjoxNjU0NjU1ODUwfQ.zhR1uZ_Mw88adT1WALiiKC8zKHHHZviI8bH4lc89Yo4
Content-Type: application/json
